server:
  port: 8002

spring:
  application:
    name: cloud-user-service
  datasource:
    url: jdbc:mysql:///jmc
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    instance-id: user-8002
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
