version: '3.7'

services:
  nacos:
    image:
      nacos/nacos-server
    environment:
      MODE: standalone
    ports:
      - '8848:8848'
      # rpc port
      - '9848:9848'

  seata:
    image:
      seataio/seata-server:1.3.0
    volumes:
      # seata config dir
      - './seata-config:/root/seata-config'
    environment:
      # specify seata config
      SEATA_CONFIG_NAME: file:/root/seata-config/registry
    ports:
      - '8091:8091'
    depends_on:
      - nacos
    restart: always