server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql:///jmc
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
