server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7001.com:7001/eureka

