server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer-feign-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7001/eureka

