server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer

  rabbitmq:
    host: 192.168.137.10
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      bindings:
        # 绑定名称，input表示把消息读进来，消费者
        # 命名规则：methodName-in-idx(from 0)
        receive-in-0:
          # 交换机名称
          destination: exg
          # 组名，同一组（就是同一队列）会竞争，不同组不会
          group: jmc

    function:
      # 填接收方法的名称（Bean名称）
      definition: receive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    # eureka中显示的状态名称
    instance-id: stream-consumer-8802
    # 当光标移到状态名称时，优先显示ip地址，而不是主机名
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'