server:
  port: 9103

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql:///user_db
    username: root
    password: root

  cloud:
    alibaba:
      seata:
        # 选择事务组
        tx-service-group: jmc_tx_group

seata:
  service:
    # 创建事务组，组内包含多个服务
    vgroup-mapping:
      jmc_tx_group: default

