server:
  port: 9002

spring:
  application:
    name: cloud-user-service
  datasource:
    url: jdbc:mysql:///jmc
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
