server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider

  rabbitmq:
    host: 192.168.137.10
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      bindings:
        # 绑定名称，output表示把消息输出去，生产者
        # 命名规则：methodName-out-idx(from 0)
        send-out-0:
          # 交换机名称
          destination: exg
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
  instance:
    # eureka中显示的状态名称
    instance-id: stream-provider-8801
    # 当光标移到状态名称时，优先显示ip地址，而不是主机名
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'